rstacruz/cheatsheets

es6.md

ES6.md links to babel.js is updated.

---

angularjs.md

https://github.com/rstacruz/cheatsheets/issues/19

Angular corrections

---

mocha-tdd.md
mocha.md

Add mocha TDD interface cheatsheet

---

ledger.md

Verbatim needs 4 leading spaces not 3.

Fixed formatting in ledger.md

---

sublime-text.md

Self-explanatory pull request.

Add Sublime Text cheatsheet.

---

css-system-font-stack.md

Fixes #41 - removed curly quotes and makes it easier to copypaste

reformatting system font stack code sample

---

immutable-js.md

Should return all caps after toUpperCase()

---

rails-migrations.md

snake_case is also an option - so adding that in.

add further clarity re: conventions

---

rails-migrations.md

add comment clarifying the use of snake_case
add comment clarifying that g can be used instead of 'generate'

add further clarifications on rails g migrate

---

phoenix.md

I am not exactly sure if that's the proper order but I believe the nesting is correct. :)

Use proper directory structure for Phoenix

---

python.md

- python.md
- Added list access example
- Added list manipulation examples
**Note**: will followup on more comprehensive examples after we play Dota.

Additional info on list and list manipulation

---

redux.md

Spell check

---

bash.md

History sub-sections:
* Commands
* Expansions
* Operations
* Slices

Add "History" section in `bash` cheatsheet

---

gnupg.md
gpg.md
gpgconf.md

* `gnupg` cheatsheet
* Added aliases `gpg` and `gpgconf`

Cheatsheet for gnupg

---

git-tricks.md

Added a command to easily rebase on top of a shared upstream if necessary.
Added a command to get an interactive view when squashing commits.

some git collaboration commands

---

react.md

Fix react cheatsheet spelling error

---

es6.md

Fix a typo

---

react.md

Fixes a typo under DOM Events

---

react.md

Updates new features

---

ph-food-delivery.md

Added Yoshinoya to Asian category.

Added Yoshinoya to list

---

_sass/2017/markdown/code.scss
cheatsheet-styles.md
polyfill.io.md

I'm gonna write a blog post to explain that "optimized" version sometime...

New cheatsheet: polyfill.io

---

bash.md

added range loop alternate

---

es6.md

Added examples of function arguments destructuring

added desctructures with defaults for array & object 

---

ph-food-delivery.md

Added Desert section with Krispy Kreme and Red Ribbon details

Added Desert section in Food Delivery

---

es6.md

Patching some small mistakes and suggesting some improvements.

Fixing minor misstypes

---

bash.md

Proper syntax is `elif` in bash

elsif -> elif

---

rest-api.md

Sources: [httpstatuses.com](https://httpstatuses.com/403), [stackoverflow](https://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses)

Forbidden should be 403 not 406

---

_includes/common/strftime_format.md
datetime.md
strftime.md

Extract strftime to /strftime

---

go.md

Update to "Named return values"

---

react.md

For completeness, and getting up to speed quickly, add initialization of the state in the constructor to States in the react cheatsheet.

add initialization of state to States

---

xpath.md

It seems this is what is intended. Sorry if I am wrong.

xpath: fix possible typo

---

bash.md

Single line and multi-line comments are added.

Adding comments section

---

rollup.md

Add [Rollup](https://rollupjs.org/) as a cheatsheet (first pass)

New cheatsheet: Rollup.js

---

elixir.md

The do a cond default you have to use `true ->` instead of `_ ->`

Elixir: fixed cond default

---

applescript.md

I have just read a book about AppleScript and learned some, and I really want to share the notes here. 
I have never used Pull Request in GitHub, so I add a few notes and give a try to it.

Add some notes for AppleScript

---

lodash.md

Trim is kind of an ambiguous term, figured a few examples would help!

Added Examples for Trim

---

postgresql.md

Hey there, just adding some other basic psql commands that I use on daily basis to make this page more useful!

Add more psql commands

---

curl.md

small typo

---

knex.md

Not sure if there was a specific reason this was hidden, seems like a pretty good overview!

Unhide Knex

---

chai.md

Chai: Add lengthOf for BDD section

Chai: Add lengthOf for BDD section

---

vim.md

I recently needed this navigation option and found the answer on [stackoverflow](https://stackoverflow.com/questions/9402607/how-to-jump-to-a-specific-character-in-vim). Figured it would fit in here as well.

Added `f` character jumps

---

cron.md

https://crontab.guru/#0_0_*_*_0

Update the "every Sunday midnight" example

---

python.md

Basically just made some things clearer by comments.

Minor improvements

---

go.md

Add the description for the For Loops and For-Range loops.

gh-pages-golang-flowControl-forLoops

---

python.md

Added enumerate and pop with index and changed a few small things.

Some improvements to python cheatsheet

---

lua.md

Lua fix, lua is one-indexed

---

tmux.md

Split commands into Windows and Sessions and added the most basic tmux commands.
**Sessions**: 
```
$ tmux new 
$ tmux new -s session_name 
$ tmux attach
$ tmux attach -s session_name 
$ tmux switch -t session_name 
$ tmux ls     
$ tmux detach  
```
**Windows**
```
$ tmux new-window
```

Tmux sessions and windows

---

curl.md

Signed-off-by: Michael Hienle <hienle.michael@gmail.com>

Add curl -L

---

curl.md

Signed-off-by: Michael Hienle <hienle.michael@gmail.com>

Add curl --silent

---

git-tricks.md

Fundamental commands on GPG signing commits.

Git: GPG signing commits

---

docker-compose.md

- Added networking.
- Added external networking

docker-compose: add networking

---

es2018.md
es6.md

Hey,
I've added a new `ES6+` examples, as requested in #386 ;)

Add some ES2018 examples to the cheatsheets

---

bash.md

Here is a less verbose push than the one listed

Adds simpler push for bash array

---

knex.md

Would be better to add `--env production` flag to all migration operations

Add production mode for knex migration operations

---

python.md

.encode() turns string into byte-like object.

Added .encode() to casting

---

bash.md

Fixed your basepath example.
Added some extras.
:D

Bash correction

---

_data/categories.yml
kotlin.md

Includes classes/functions/variables/control flow. Would love to add a section in the future about destructuring, delegates, and some other helpful tricks but wanted to get out a starting point.

Added Kotlin Cheat Sheet

---

goby.md

(Retry from https://github.com/rstacruz/cheatsheets/pull/464)
We reviewed and shortened our cheatsheet.
Best regards,

New: Goby language

---

scp.md

add(cheatsheet): scp

---

composer.md

It has some mistakes and I made it more general as well as noting best practicing. Also corrected some grammar issues. (Might have added others :))

Improving composer cheatsheet

---

bolt.md

This adds a cheatsheet for [bolt](https://github.com/puppetlabs/bolt)

Create bolt.md for puppet-bolt

---

git-branch.md

- Added branch listing
- Added branch deleting

updated git-branch.md

---

python.md

Provided correct description for list elements replacement

Updated python.md

---

jsdoc.md

https://github.com/jsdoc/jsdoc/issues/1197

Add promised type

---

bash.md

Updating printf functions to print numbers and floats.

Updating printf functions

---

homebrew.md

Publish frequently used Homebrew Cask commands which I have found useful.

Publish frequently used Homebrew Cask commands

---

chef.md

Chef has changed a bunch since the last update.

Update chef hints to be more modern

---

docker.md

hi,
added some useful cleanup commends to docker

add some clean up commends

---

react.md

Added a "Hooks (New)" section to React page.
Preview:

Add React Hooks

---

stencil.md

Fixes a broken link related to updating arrays in Stencil.

Fix broken link for Stencil

---

dockerfile.md

Add ARG syntax in dockerfile. https://docs.docker.com/engine/reference/builder/#arg

Add ARG syntax in dockerfile.md

---

superagent.md

- Better identation
- Markdown with correct syntax highlighting
- Comment for every property
- Added more properties (with examples)

Improved superagent.md with more properties

---

homebrew.md

Mention brew doctor as a common and useful brew command

brew doctor

---

.github/workflows/rebase.yml
.travis.yml

- Update travis config
- Fix GitHub workflow config
- Add proper support for `/rebase` (hopefully) via [cirrus-actions/rebase](https://github.com/cirrus-actions/rebase)

Add Slack notifications to Travis config

---

semver.md

Fix typo of Hyphenated ranges

---

docker.md

I especially struggle how to build the pipe to less or other programs. (This is of probably very much bash specific)

Add docker logs instructions

---

docker.md

Add --build-args argument in docker CLI. https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

Add argument --build-args in docker

---

docker-compose.md

More info. https://docs.docker.com/compose/compose-file/#volumes

Added named volume in docker-compose.md

---

awscli.md

Add EC2 instance termination command.

Add EC2 instance termination command

---

homebrew.md

brew search command

---

python.md

referenced string documentation here: https://docs.python.org/3.9/tutorial/introduction.html

escape characters for string

---

knex.md

Added
- Knex seed commands.
- `-x ts` option to create TypeScript files.
- Format bash markdown text to highlight comments.

Update knex.md with seed docs.

---

docker-compose.yml

fix docker bug when building development environment

---

vim.md

I found this one while messing around in vim.

Swap "Previous/next end of word" shortcuts in vim.md

---

curl.md

Include the HTTP-header in the output

Display -i, --include

---

yaml.md

Add Reference Content to YAML Cheatsheet

[YAML]: Add Reference content

---

CONTRIBUTING.md

hello sir, I fixed the command to install yarn on the docker-compose

fix command First-time setup docker

---

homebrew.md

brew upgrade to Upgrade all packages

Add brew upgrade to Global commands

---

python.md

There was some minor mistakes in the file manipulation section, so I just rectified them.

Correction of small typing errors

---

vim.md

Fix style of words section in vim.md

fix words section

---

css-flexbox.md

added more container alignment options

css-flexbox.md

---

go.md

Added function implementation of new() for getting a pointer.

Added new() to get pointer

---

spacemacs.md

File will remain intact i.e. no changes will be made to your file.

Delete current buffer

---

lodash.md

Not sure if this was renamed at some point but there's no "findRight" in lodash, just findLast.
https://lodash.com/docs/4.17.15#findLast

findRight is actually findLast

---

bash.md

Added a way of getting the last element from the array for `Bash scripting cheatsheet`
https://devhints.io/bash

Add a way to get the last element

---

lodash.md

[Lodash] Fix padding

---

vim.md

…lipboard
These shortcuts will allow user to copy paste from/to system clipboard. Used this answer from stackoverflow for reference:-
[https://stackoverflow.com/a/11489440/2376317](https://stackoverflow.com/a/11489440/2376317)

vim: Added system clipboard copy-paste shortcuts

---

sass.md

Add `Nested Properties`
and how about add `else if`?
sometimes I get confused `elif`, `else if`, `if else`

sass: Update sass.md

---

lua.md

lua: Fix elseif conditional typo

---

sed.md

Added a sed command i use a lot when checking logs.

sed: Added command for excluding lines while printing

---

vimscript-functions.md
vimscript.md

#740 and another bug in vimscript cheatsheet.
Great cheatsheet by the way - I always use it when I code vimscript.

vimscript: Function stridx return value is an index

---

netlify.toml

Fix redirection for URL's like `/sh` -> `/bash`.

Tech: fix 301 redirects

---

_sass/2017/components/h3-section.scss
_sass/2017/components/main-heading.scss
bash.md
enzyme.md
enzyme@2.md
factory_bot.md
fastify.md
go.md
httpie.md
sass.md
xpath.md

Add support for introduction sections in some cheatsheets.

Add introduction sections

---

fastify.md

This is current as of https://github.com/fastify/fastify/commit/972f2e7b124d4ca692c25c1c4b1be46c6913c0e9

Fix link to serialization document

---

minitest.md

This pull request updates Minitest syntax changes that are visible in the readme of the [repo](https://github.com/seattlerb/minitest).
Thanks for making such a wonderful cheat sheet resource.

Update to new Minitest namespace synatx

---

slim.md

I collected some ways to prepend and append whitespaces in Slimlang.

Add Slim whitespacing section

---

docker.md

I always have to lookup which side is the container and which one is the host side. Therefore this comment would really help me.

docker: Supply more helpful docker run -p description

---

go.md

fix the broken indentation and align the indentation with other examples

fix indentation in go.md

---

_includes/common/moment_format.md

Add an example to show how to add custom text into moment.js date format expressions.

Add example in moment.js cheatsheet

---

stylus.md

available here https://stylus-lang.com/docs/variables.html#property-lookup

Updated Property lookup to reflect new docs

---

scp.md

added port param

---

c_preprocessor.md

I added Stringification to the C Preprocessor.
I also fixed an issue with Token Concat.

Add Stringification to C Preprocessor

---

makefile.md

I think these are more informative and precise examples for assignment expression.

Update assignment section "="

---

curl.md

Add curl -F

---

ember.md

It has been a while since Ember has moved away from views to components :)

Update Ember syntax

---

robots.txt

Not sure if Google likes the robots.txt but removing it should reduce complexity.

Empty out robots.txt

---

python.md

Fixing a spelling issue in the Python section.

fix spelling issue in Python

---

fastify.md

As of https://github.com/fastify/fastify/blob/4290f2843c38ec823d1592018f0def783e2a88ad/README.md

update fastify validation and middleware reference links

---

mysql.md

GROUPBY Space required

---

fish-shell.md

- keybindings updated
- Variables, Arithmetic, String manipulation, Loops, Abbreviations new sections
- Conditionals, Completions updated
...

Fish shell page update

---

composer.md

Please see `composer outdated --direct --help`

Add composer outdated --direct

---

elixir.md

This is a powerful construct when checking multiple conditions for a single happy path

Elixir: Add `with` Example

---

fish-shell.md

Update fish.md (formatted from #1758)

---

sass.md

The new @use rule has been added, and a warning has been given regarding the phasing out of @import.

Added @use rule

---

rails-models.md

- Ordered callback the life cycle
- Add missing methods including before and around

RubyOnRails: Order ActiveRecord callbacks and add missing methods

---

bash.md

Add tr command description, few options and example

Add tr command to bash cheatsheet

---

rspec.md

This is my first PR here so sorry if there is not enough examples, let me know if I should add more.
This PR just adds an example of how you can use the `.or` method for chaining a logical or condition to the same expectation.

Add Logical Or example to RSpec

---

docker-compose.md

Updated docker-compose.md

---

dockerfile.md

Hey, just wanted to share what I learned recently to transfer from the (b)ash cheatsheet onto the image build process. ;c)

Add usage of strict shell

---

react.md

https://reactjs.org/docs/fragments.html#keyed-fragments
If you are using map with fragments you require keys in it

fix react confusion Fragments don't require keys!

---

bash.md

Added Bash Hackers Wiki link to the Introduction section, as this is just as useful as the other two.

Added link to Introduction section

---

docker-compose.md

source: https://docs.docker.com/compose/compose-file/#healthcheck

Add Healthcheck cheatsheet

---

netlify.toml

Bump runtime versions (Node.js v18)

---

docker-compose.md

source: https://docs.docker.com/compose/compose-file/#depends_on

docker: Add depends_on long syntax

---

css-grid.md

According to MDN Web Docs, subgrid is a value for grid-template-columns and grid-template-rows properties not the display property.

Update subgrid value

---

mysql.md

Fix typo in MySQL backup command.

fix(mysql): fix mysql backup typo

---

gnupg.md

As per [gpg2 stable branch](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=doc/gpg.texi;h=cd8ded98285dcb30b27ec318f763b8447c4ec8b3;hb=refs/heads/STABLE-BRANCH-2-2#l504)

Fix merge flag name

---

vim.md

In the Document section, "Move down/up by n lines"

Added 2 movement shortcuts

---

capybara.md

[Docs](https://www.rubydoc.info/gems/capybara/Capybara%2FRSpecMatchers:have_current_path)
[Maintainer discussing the method](https://stackoverflow.com/a/33055907/1511504)

Include have_current_path into expectations

---

react-router.md
riot.md
rspec-rails.md
rspec.md
rst.md
sequel.md
sequelize.md
sinon-chai.md
social-images.md
spine.md
superagent.md
tmux.md
typescript.md
ubuntu.md
umdjs.md
underscore-string.md
unicode.md
vim-digraphs.md
vim-easyalign.md
vim-rails.md
vimscript-functions.md
vimscript-snippets.md
virtual-dom.md
vows.md
yargs.md

Updates some cheatsheets to the 2017 format.

Content formatting update

---

_data/google_analytics.yml

Update Google Analytics settings

---

js-date.md

Made all the dates be consistent to each other.

Consistent Dates in js-date.md

---

typescript.md

Changed "Conditinal" to "Conditional"

Fix spelling

---

bash.md

This add additional line in in the brace expansion section

Add multi range brace expansion to bash.md

---

screen.md

Changed basics section to start/detach/list/reattach since thisis the dominant usecase

Improve screen

---

yum.md

This is to address issue number: #372 
See the documentation used : https://access.redhat.com/sites/default/files/attachments/rh_yum_cheatsheet_1214_jcs_print-1.pdf

Yum cheatsheet

---

_data/content.yml
_sass/vendor/modularscale/_modularscale.scss
_sass/vendor/sanitize.css/sanitize.scss
fish-shell.md
goby.md
promise.md
regexp.md
scp.md
vim.md

Fix some typos

---

jsdoc.md

Added the newer import syntax that works on TS 5.5

Update jsdoc.md to use the @import keyword

---

packs.md

Adding a page per `packs` documentation on https://github.com/rubyatscale/packs
`packs` is a system to modualize ruby projects.

:memo: Add packs.md

---

jsdoc.md

Add common keywords to js docs cheatsheets

Add additional keywords to jsdocs.md
