rstacruz/cheatsheets

react.md

This method does not exist. At this point in time the component is deleted, so you have to use componentWillUnmount instead.

Removed componentDidUnmount

---

tig.md

This is useful for navigating the history of a single line with `,` and `<`.

Comma blames from parent commit

---

phoenix-routing.md

2 identical function call would return different output in 
```
user_path(Endpoint, :index)                 #=> /users
...
user_path(Endpoint, :index) #=> "http://localhost:4000/users"
```
but in fact the last one should use user_url as indicated in doc http://www.phoenixframework.org/docs/routing

Use user_url instead of user_path in last case

---

python.md

Typo: `import regex` to `import re`
[Python 2.7](https://docs.python.org/2/library/re.html)
[Python 3+](https://docs.python.org/3.6/library/re.html)

python: correct to 'import re'

---

es6.md

Not aware of String.prototype.contains becoming an ES standard, however, String.prototype.includes is functionally equivalent. 
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

Contains not a function, update to includes

---

vim.md

noticed it because of a comment at https://devhints.io/vim where this sheet is referenced

fixed an error and added a relevant cheat

---

es6.md

Credits for spotting the error: [this comment](https://devhints.io/es6#comment-3599862808) on the cheatsheet page.

ES6: Use for..of in destructuring with loop example

---

es6.md

```
var scores = [22, 33]
var [math = 50, sci = 50, arts = 50] = scores
```
In the end, sci is equal to 33 (and not 23) :)

Fixed destructuring example value

---

elixir.md

The charlist change is needed because all Elixir core is using the
"charlist" version. We also should use to keep consistency.
Also, to_char_list/1 is deprecated since Elixir 1.5.
References:
- https://github.com/elixir-lang/elixir/blob/ed98604dc3ce7e9a0b057350b13a6de25a71557a/lib/elixir/pages/Deprecations.md#table-of-deprecations
- https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html

Elixir: Fix Enum example and rename "char list" to "charlist"

---

vim.md

Currently `^` is being used as `ctrl` but this could be confusing as `^` within vim goes to the start of the line.
Changing it to `<C-*>` should make it less confusing. 
It'll also be more consistent with how it's used in `.vimrc`.

✏️ Change ctrl caret to be less confusing

---

vim.md

Original document alluded to the fact that cases can only be changed from `visual` mode. They also work in `normal` mode.

Vim guide - minor wording change

---

bash.md

Fix a small error in the *Conditionals* section of the **Bash Cheatsheet**.
The Bash syntax allows for `elif` while the cheatsheet uses `elsif`.
Great job by the way!

Change elsif to elif

---

CONTRIBUTING.md

Developer notes::Starting a local instance
1. Install **Ruby**: https://rubyinstaller.org/
* After the installation check the box and type `3` to select the 3rd option
* Add `C:\msys64\usr\bin` to PATH env variable 
* Add `C:\Ruby24-x64\bin` to PATH env variable
2. Install **yarn**: https://yarnpkg.com/en/docs/install#windows
3. Install **jekyll** via command prompt: `gem install jekyll bundler`
4. Install **nodejs && npm**: https://nodejs.org/en/download/
4. Install **webpack** via command prompt: `npm install -g webpack`
5. If you have any issues after installing ruby, like `HOMEPATH` is not defined, then execute the below commands:
```bash
SETX HOMEDRIVE %SYSTEMDRIVE% -m
SETX HOMEPATH \Users\%username% -m
SET HOME=%SYSTEMDRIVE%\Users\%USERNAME%
SETX HOME "%HOME%"
```
Go wherever the …

Windows quickstart tutorial on CONTRIBUTING.md

---

phoenix-conn.md

Even though it is, in itself, a misspelling! https://en.wikipedia.org/wiki/HTTP_referer

Fix spelling of referer

---

adb.md

Covers some basic usage of adb, including starting apps, collecting logs, and pushing/pulling files.

Adds cheetsheet for Android Debug Bridge (ADB)

---

elixir.md

The case condition was missing in the elixir documentation.
I remove the 3 column distribution and now looks like this

Add Case control flow structure in elixir docs

---

makefile.md

As documented in the [GNU Make manual](https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html), `$%` is only used for files within archive files (which is a feature rarely used in my opinion). The automatic variable `$*` represents the matched part in implicit rules (%.o: %.c), e.g., "foo" for "foo.c".

correctly describe "$*", remove incorrect "$%"

---

react.md

IMHO, the previous example leads people to confusion into thinking that returning a element with a `<div>` and `<React.Fragment>` are equivalent, yet they aren't. This should clarify things up a bit and accentuate the difference.
Also, added the fragments example to the new features section.

[react] [docs] make React.Fragment example more clear

---

flow.md

This seems more reasonable, taken from the official Flow docs as well.

[flow] modify minimal example to typing React components

---

flow.md

This fixes an incorrect example in the flow cheatsheet. An explanation is below:
For an optional property, the property can either be undefined, otherwise must be any value that is not null. The example was showing  the incorrect output of a setting the value to null.
An example of the failure with the same example as in the sheet can be found here to be certain that this case does in fact throw an error:
https://flow.org/try/#0C4TwDgpgBAggNgIwK4FsoF4oG8BQUoB2AhihAPwBcUAzsAE4CWBA5jgL544DGA9gbVCJV4yNJixQ2UAPTSogZHIoAeQDSOIgDpipDFADkAIThIIe-OZlzFq9VpLRMBJHDgWLshcpUAaKAFUACygeIIBaQS5gJCIXEEIeYGCAa1ttBygkAgATCAAzJggs8w9rFSA

Fixed incorrect flow type output

---

enzyme.md

Use prop instead of props when returning the prop value for a node with given key.

correcting enzyme props to prop

---

git-log-format.md

fixed refs format variable on git-log

---

bash.md

they check to see if the strings are equal or not... 
Just thought its an essential comparison that should be in the cheatsheet.

Added 2 String Comparison Conditionals

---

sass.md

In `sass.md`, under *Modifying HSLA* the function `compliment($color)` should be `complement($color)`.

changed compliment() to complement() in sass.md

---

vim.md

Add vim shortcut notation info so that people know how to understand commands like `<C-C>` or `<Cr>` that can initially be confusing.

Add key shortcut info.

---

find.md

The units of the size command are not straight-forward. The default
file size unit is counter-intuitively 512-bit blocks. This patch
includes a cheat sheet for the ability to filter files based on its
size and the various units that are accepted by the find command.

find: Include file size conditions

---

bulma.md

In cases where WYSIWYG editors generate the HTML content of the page,
the content does not have Bulma classes applied to them, which means
they'll be unstyled because that's just how Bulma works. An `<h1>` tag
does not have a style until you add the class `title` to it.
To handle this case, wrap the generated content with `.content` class.

Add cheatsheet on handling generated content with Bulma.

---

zsh.md

Adding to cheatsheet when =(...) is more appropriate than <(...) and
vice-versa.

zsh process-substitution: <(...) vs =(...)

---

factory_girl.md

It was incorrectly categorized as a JavaScript library, but it was meant to be a Ruby library

Fix "Factory Girl" category

---

makefile.md

Fixes #992 
The description of the ":=" and "=" assignment operators were flipped. As documented in the GNU make manual (https://www.gnu.org/software/make/manual/make.html#Reading-Makefiles), the ":=" assignment operatory is the immediate assignment operation and "=" is the deferred assignment operation. This change switches the descriptions to correspond to the correct operator and augments the description to clarify the behaviour.

Correct description of ":=" and "=" operators

---

jsdoc.md

Escape the '|' in the "Multiple types" row.

jsdoc.md: Fixed Types table

---

Makefile
_includes/head.html
_sass/2015/base/normalize.scss
_sass/2015/base/typography.sass
_sass/2015/base/utils.sass
_sass/2015/components/about-the-site.sass
_sass/2015/components/big-button.sass
_sass/2015/components/brief-intro.sass
_sass/2015/components/full-image.sass
_sass/2015/components/hint.sass
_sass/2015/components/hljs.sass
_sass/2015/components/next-article.sass
_sass/2015/components/post-headline.sass
_sass/2015/components/post-icon.sass
_sass/2015/components/post-index.sass
_sass/2015/components/post-list.sass
_sass/2015/components/site-header.sass
_sass/2015/components/social-list.sass
_sass/2015/elements/body.sass
_sass/2015/elements/code.sass
_sass/2015/elements/table.sass
_sass/2015/helpers/blink.sass
_sass/2015/helpers/general.sass
_sass/2015/helpers/margins.sass
_sass/2015/style.sass
assets/2015/style.sass
assets/2015/style.scss

There was a hard dependency on the styles in `ricostacruz.com/til`, which are no longer available after redesigning that website.
This adds those styles here. These should no longer be necessary after updating to `devhints-engine` though!

Fix styles for older pages

---

css-grid.md

I noticed three areas where the guide had the misspelling "tamplate."

Fixing typos "tamplate" -> "template"

---

ansible-guide.md

The external links for inventory and playbook where displaced and needed to be swapped.

Corrected links to Ansible documentation

---

es6.md

Added missing ')' at the end of `fat arrow` example

Added missing ')'

---

.gitpod.yml

This is going to cache `bundle install` dependencies in docker image that is used for gitpod so that contributors doesn't have to wait for it to finish on each run. (Makes the environment to be instantly ready for work instead of waiting 57 seconds)
**Heads-up:** This requires authentification from https://github.com/marketplace/gitpod-io/ to be allowed for this repository.

gitpod: Cache 'bundle install'

---

jsdoc.md

Fixed what I think is a typo based on this:
https://jsdoc.app/tags-param.html#multiple-types-and-repeatable-parameters

Fix JSDoc function param with multiple types

---

docker-compose.md

> SHORT SYNTAX
> Either specify both ports (HOST:CONTAINER), or just the container port (an ephemeral host port is chosen).
https://docs.docker.com/compose/compose-file/

Fix ports syntax

---

_includes/common/moment_format.md

Fixed format's to correct `Mo` example column (previously listed "1st..31st"; now only goes up to 12th).

MomentJS: Only 12 months for `Mo`.

---

awscli.md

Using multiple aws credentials is a very common scenario, so hinting to the `--profile` option is highly encouraged.

Added aws configuration profile option

---

tmux.md

tried on fedora 30 and mac os mojave (tmux from brew), horizontal pane are **C-b "** and vertical pane are **C-b %**

fix tmux pane creations

---

enzyme.md

`getNode` and `getNodes` methods are depreciated and no longer in use. They are renamed to `getElement` and `getElements` instead. 
See Enzyme docs here: 
- https://airbnb.io/enzyme/docs/api/ShallowWrapper/getElement.html
- https://airbnb.io/enzyme/docs/api/ShallowWrapper/getElements.html

Update obs. Enzyme methods 'getNode' & 'getNodes'

---

osx.md

- /etc/hostconfig is not supported anymore since Yosemite
- added 3 options to disable spotlight indexing
- fixed system utils typos.

OSX spotlight and system utils changes

---

bash.md

`< file.txt | cmd` only works in zsh, not bash (as of bash 5.0.11).

bash: fix line reading example

---

enzyme.md

Instead of `.props('name')`, use `.prop('name')` to access a single prop's value for testing

Updated accessing a single prop's value

---

tmux.md

Was originally -s instead of -t, so it would not work.
This fixes it.

Fixed tmux attach.

---

badges.md

The link to the gitter repo should not contain the user in the link to the community, instead the `REPO/GITTERROOM` should be used.
For example:
```
[![Gitter chat](https://badges.gitter.im/rstacruz/cheatsheets.png)](https://gitter.im/cheatsheets/community "Gitter chat")
```

Fix: Use room and remove user from gitter room link

---

react.md

While it works for this example, it's usually an error to leave out the dependencies; it would run the effect every render, even when the relevant values did not change.
We can add more explanation for the deps part, but I think it's a low-hanging fruit for a cheatsheet.

React Hooks: Add deps to useEffect

---

badges.md

A second copy of the MIT license badge seems to have slipped in right after the first one.

Remove duplicate MIT license line from Badges

---

capybara.md

Capybara renamed click to click_on
[From their history](https://github.com/teamcapybara/capybara/blob/master/History.md): 
> 
> Version 0.4.0.rc
> Session#click has been renamed click_link_or_button and the old click has been deprecated
> 
> Version 0.4.1
> New click_on alias for click_link_or_button, shorter yet unambiguous. [Jonas Nicklas]

Update capybara.md - click => click_on

---

js-array.md

Rearranged so that `Immutable` is above `Mutative` in both examples.

Small improvement

---

rest-api.md

service.com is a real domain name, and could potentially have a real API on api.service.com
example.com is specifically reserved by IANA and thus will never have an API on it. It is designated to be used in scenarios like this. See [RFC 2606](https://tools.ietf.org/html/rfc2606#section-3) for more information.

Use example.com instead of service.com

---

go.md

Fix a Very small error in # Methods -> Receivers

Fix Typo in Golang cheatsheet # Methods -> Receivers

---

factory_bot.md

Update static attributes using dynamic instead of deprecated one. Static attributes, without a block, are deprecated and will be removed in factory_bot 5.
example of deprecated static attribute:
`  admin true`
example of dynamic attribute:
` admin { true }`
more read : 
- https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#static-attributes

factory_bot: Update static attributes using dynamic

---

bash.md

I always forget if `else` is to be followed by a `;` or not. Add it to the conditionals chapter where I would expect it.

Bash: add `else` example

---

vim.md

Works pour `{}`, `()`, `[]` and also `/* */`, `#ifdef` and other usual delimiters
in programming languages. See ':help %'.

vim: Added '%' as a quick delimiter navigator

---

emmet.md

Fixed a typo in emmet
section>p gives <section><p>...</p></section>
Earlier it was <section><pt>....</p></section>

emmet: Fixed a typo in Emmet Cheatsheet

---

CONTRIBUTING.md

Capitalized first letter on "**Keywords**," "**Description**," and "**Intro**" to be more consistent with document's current style.

Formatting: capitalized first letter on some headings

---

flow.md

The example given for width subtyping is marked good, but it is not. Fix it with one which really addresses the concept.
Rewrite the example for Exact Object Type as well for a clear comparison.

Flow: Fix the example for width subtyping

---

vim.md

• `:ff=unix` → `:set ff=unix`
• Remove random `ff` from navigation table as it was messing up the formatting:

vim: Fix two minor errors

---

phoenix-migrations.md

adding `precision: 10, scale: 2` will result in an exception on migration due to malformed sql. precision and scale apply to decimal

phoenix-migrations: changed precision to apply to decimal

---

bluebird.md

Don't mark [`Promise.prototype.finally`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally) as non-standard/Bluebird extension.

bluebird: `Promise.prototype.finally` is standard Promise API method

---

jsdoc.md

It's probably too much to put in all keywords, but we can at least link to the official list.

[JSDoc] Link to the full list of keywords

---

composer.md

The commits aims to add examples for passing versions to `composer require` and `composer update` commands

composer: Add examples of how to pass versions

---

flow.md

Update doc links in `flow.md`:
* Dynamic object keys 
* Enums
* Type aliases
* Generic classes
* Interfaces
* Functions

flow: Update doc links

---

bash.md

- using `=` just throws an error!
- `200` limits the result to 200 possible numbers starting with 0! so the maximum is 199.
- added `$` straight before `RANDOM` to be on the safe side.

bash: Correct mistakes at $RANDOM

---

xpath.md

we need to use `.//` instead of `//` inside the predicate
Before: `//section[//h1[@id='hi']]` -- This returns `<section>` if **document** has an `<h1>` with `id='hi'`.
After: `//section[.//h1[@id='hi']]` This returns `<section>` if it has an `<h1>` **descendant** with `id='hi'`.

xpath: Fix nesting predicates

---

tig.md

Widely unknown, but as useful as `git -C`.

tig: Add `tig -C` invocation tip

---

.gitpod.yml

Hi! 👋
I saw in `CONTRIBUTING.md` that one can start a preview server by running `yarn install`, `bundle install` and `env PORT=4001 yarn run dev`.
I've thus added these commands to the `tasks` in `.gitpod.yml`, so that Gitpod automatically runs them when you start a workspace for this repository.
You can test this Pull Request by opening my fork in Gitpod: https://gitpod.io/#https://github.com/jankeromnes/cheatsheets
This is what it looks like:

gitpod: Make Gitpod's automated dev setup automatically run Jekyll and Parcel

---

emmet.md

Hello I noticed that the class for "IDs and Classes" was missing
in Numbering the last example is missing and I did not modify it but I do not get the same result for : ul>li.item$@-*3 
<ul> 
<li class="item1@-"></li>
<li class="item2@-"></li>
<li class="item3@-"></li>
</ul>

emmet -  missing item

---

tig.md

`s` key value stands for Status instead of Stage view.
Stage view can be accessed with `c` key value.
Reference: http://jonas.nitro.dk/tig/manual.html#view-switching

Tig - Fix view name for s key value

---

git-branch.md

`--force-with-lease` is safer than `--force` as it checks that you are up-to-date with the remote branch.

Add the mention of push --force-with-lease

---

bash.md

I think the description for the special parameters `$@` and `$*` was somehow incomplete and possibly misleading. The only difference  is that one of the description reads "starting from first", which I don't quite understand. It suggest somehow the other positional parameter starts in a different parameter? I believe that can be misleading, and it does not explain the essence of the parameters.

Updated description for arguments section

---

elixir.md

Added Map.from_struct and Kernel.struct to maps section.

Add Map.from_struct and Kernel.struct to maps section of Elixir cheatsheet

---

xpath.md

`[1]` is only equivalent to `:first-child` if all the children are of the same type. Using `:first-of-type` would be more accurate. I changed either CSS or XPath depending on which seemed to make the example more useful.

Fix a few examples that were using wrong CSS pseudo-classes

---

python.md

Expanded the cheat-sheet with:
- *, ** as expansion arguments for lists and dicts./
- A Tuple section
- 'mutable' and 'immutable' notation behind the Tuple and Lists header.

Expanded the python cheat-sheet

---

vimscript.md

Replace the line "return true" with "return 1". As the document explains
elsewhere, Vimscript does not have booleans.

vimscript: Fix invalid code example

---

bash.md

This is an very useful parameter expansion that is not widely known. You see this pattern often in bash one-liners like this:
git clone https://example.com/the/reponame myfolder && cd $_
Well worth including in the cheatsheet.

Add special parameter $_ to bash cheatsheet

---

ledger-csv.md

Transaction code is an arbitrary code assigned to a transaction (check number, invoice number...). It is specified between parentheses just before the transaction description.
Transaction notes are written as comments after a semicolon.
Example:
```
2021-10-30 * (ABC123) Stuff
Expenses:Things        P 50.00    ; Something I need to remember about this transaction
Assets:Cash
```

Adds column names for transaction code and transaction notes. Fixes typo 'expneses'.

---

org-mode.md

According to https://orgmode.org/manual/Emphasis-and-Monospace.html,
it should be `=verbatim=` and `~code~`

Correct the emphasis markup

---

go.md

The waitgroup that is defined in main() with var wg sync.WaitGroup, only has scope inside the main() function. The doOperation() function will not know about it and so the defer wg.Done() line will result in a compile time error. The waitgroup needs to be passed as a parameter to the doOperation() function.

Fixed bug in WaitGroup example

---

jsdoc.md

Async is so prevalent these days, felt like it was important to include in a cheatsheet.

Add @async to JSDoc `Other keywords` section

---

bash.md

Stylistic fixes / shellcheck.net violations:
* Prefer lower case for private variables everywhere
* Best practices: quoting
* Reading lines with `while read`: avoid useless `cat`
* Mark backticks as obsolescent
New examples and amplifications:
* Add example of unquoted wildcard and option
* Redirection example >file 2>&1
* Redirection example: diagnostic message to stderr
* `printf` examples: format string is repeated

bash.md: update with best practices

---

regexp.md

There are terms to reference captured group that was not added.
\1 will replaced by value of first captured group.

added capturing group reference term

---

regexp.md

^ and $ work differently in multi-line pattern which are different from \A and \Z.

fix: make the meaning of ^ and $ more precise

---

tig.md

The last update was in 2018, and some shortcuts were wrong, and many were missing. This update adds the most pertinent shortcuts in the most used tig views. This update matches tig version 2.4.1.

Update tig cheatsheet

---

tig.md

There is no newline between the header and the table body, resulting in a rendering issue at https://devhints.io/tig.
This PR adds a newline after the section header.

tig: Fix traling newline in header

---

vim.md

A short cheat sheet is more efficient and user-friendly than a bloated manual, as it presents only the most essential information in a clear and concise format. Furthermore, having a compact cheat sheet allows for easy accessibility and quick reference, making it more likely to be used and retained in a time-sensitive or high-pressure situation.
This is why I propose to remove some of the commands to improve readability.
When typing `:q` in vim with unsaved changes, vim refuses to quit and suggests to use `:q!`. This is why I propose to remove this and the `:qa!` equivalent from the cheat sheet. The information is not needed here because when u need it, vim already suggests it to you.

Removed :q! and :qa!

---

bash.md

The ${foo/%from} is an alternative form of long suffix removal.
Likewise, he ${foo/#from} is an alternative form of long prefix removal.
Test cases:
~~~bash
###
###
foo=gododa
r=${foo/#g*d}
r=${foo##g*d}
r=${foo#g*d}
###
###
foo=agogod
r=${foo/%g*d}
r=${foo%%g*d}
r=${foo%g*d}
~~~

Alternative form of long prefix/suffix removal

---

clip.md

Other [CLIP](https://github.com/command-line-interface-pages/prototypes/tree/main/clip-view) project tools will be added later. Accepting this PR will help my project gain more popularity, thanks for understanding. 
This project goal is to replace [TlDr](https://github.com/tldr-pages/tldr) project completely. CLIP project already has better client in terms of feature amount compared to [TlDr official one](https://github.com/tldr-pages/tldr-python-client) and third party clients. To be specific: it [provides](https://github.com/command-line-interface-pages/syntax/blob/main/syntax.md) more expressive and clear syntax for writing pages, [color theme](https://github.com/command-line-interface-pages/prototypes/pull/22) support. Even TlDr maintainers help me to develop it I think their main …

Add Command Line Interface Pages (CLIP) page syntax examples

---

capybara.md

Removes the bad negative example and adds a new one that still has bad performance.
It use to be that `not_to` would wait
in a non-performant way:
https://www.cloudbees.com/blog/faster-rails-tests 
but now it it no longer waits: 
https://github.com/rubocop/rubocop-rspec/issues/378#issuecomment-463250177

Remove bad negative example from capybara sheet

---

bash.md

This PR replaces dead links to `bash-hackers.org` (the domain has expired on 2023-04-13 and currently is taken by cybersquatter) with Web Archive ones.
Replaces: #1992 #2001 #2003

bash: Recover broken links using Web Archive

---

tar.md

Just a very little typo fix in the `tar.md` document

fix typo in tar.md

---

docker-compose.md
docker-compose.yml
fish-shell.md

I was using this cheatsheet to brush back on fish conditionals. 
Turns out when you use something like 
```fish
test $TMUX_PROGRAM == '/usr/bin/tmux'
```
An error is returned : 
`test: unexpected argument at index 2: '=='`
```fish
test $TMUX_PROGRAM = '/usr/bin/tmux'
```
Works fine. 
The official documentation uses the same operator https://fishshell.com/docs/current/cmds/test.html
I changed the documentation to follow the newer docker compose out of the box and summarized the migration for everyone.
The official documentation : 
https://docs.docker.com/compose/
https://docs.docker.com/compose/migrate/
I also took the opportunity to remind a few others useful docker compose commands, just in case they didn't exist back in last update in 2020.

Two changes : Correction on Fish cheatsheet & version update on Docker compose 

---

bash.md

Either use the `function` or `()` but not both, it's redundant.

Remove redundant syntax

---

capybara.md

```ruby
!expect(page).to have_button('Save')
```
The above case is a new Bad case added by https://github.com/rstacruz/cheatsheets/pull/1798 . It is designated as Bad due to performance issues, but it is not actually a Negative example. In practice, the following would be the same test:
```ruby
expect(page).to have_button('Save')
!expect(page).to have_button('Save')
```
This is not an example that will appear on the capybara cheat sheet, because it is a problem with how RSpec is written. I think it should be removed because it creates confusion.

Remove a case that is not negative examples in the capybara sheet

---

rspec.md

No arg defaults to :each not :all 
https://www.rubydoc.info/github/rspec/rspec-core/RSpec%2FCore%2FHooks:before

Fix before/after with no arg

---

polyfill.io.md

A warning is added to the polyfill.io sheet in relation to the malicious script that is now being served by polyfill.io. Removed all links to that domain.
The code snippets have also been updated to use Cloudflare's script instead. This allows users to keep using polyfill securely while they move their codebase away from using this polyfill.
Cloudflare press release: https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk
Fixes #2145

Include warning on polyfill.io sheet; use CF instead

---

vim.md

New shortcut `:q!` added for quit without checking changes in `vim.md` file.

New shortcut for vim.md

---

.github/workflows/build.yml

The `actions/cache`acrion uses the deprecated Node 16 runtime. Upgrading actions/cache should fix this.

Update cache GitHub action

---

python.md

Fixes missing code highlighting in half of the Python code snippets.
The top half of the page had code examples formatted as code blocks with 4 space character indentations and no syntax highlighting as a result.
The bottom half on the other hand, used code blocks surrounded by "```py" formatting brackets which hints to many markdown renders that syntax highlighting should be applied.
This unifies the code blocks in the top half of the page to use the same formatting syntax used in the bottom half with syntax highlighting.
This change was prompted by requests to add the syntax highlighting in comments on the https://devhints.io/python page.

Add missing syntax highlighting to python.md

---

src/components/V2017Sheet/SearchForm.astro

I was looking for notes and then when i was searching svelte i couldn't see the possible search hits.so i turned autocomplete off now it works like charm.

fix: annoying browser suggestions

---

markdown.md

[GFM](https://loilo.github.io/gfm-preview/) now supports the ability to embed Base64 encoded images in Markdown.

Embedded Images in Markdown
